version: '3'
services:
  fed:
    build: ./FED
    ports:
      - "80:80"
    volumes:
      - ./FED/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./FED/config/nginx/ngnix.conf:/etc/nginx/ngnix.conf
    depends_on:
      - service
    networks: 
      app_net:
  service:
    build: ./Server
    depends_on:
      - prisma
      - judge
    environment:
      JUDGE_HOST: http://judge.pdsuojservice:7767
    networks: 
      app_net:
        aliases:
          - api.pdsuojservice
  judge:
    image: xluos/pdsuoj-judger:0.0.2
    cap_add:
      - SYS_PTRACE
    networks: 
      app_net:
        aliases:
          - judge.pdsuojservice
  postgres:
    image: postgres:11
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app_net
  prisma:
    image: prismagraphql/prisma:1.30
    container_name: prisma
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          postgres:
            connector: postgres
            host: postgres
            port: 5432
            user: postgrestest
            password: postgrestest
            migrations: true
    networks:
      - app_net      
volumes:
  database: {}
networks: 
  app_net: